name: vsixbuilder

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build_vsix_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and tools
        uses: jdx/mise-action@v2

      - name: Setup VSCE
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: |
          vsce package --baseContentUrl https://github.com/GitGuardian/gitguardian-vscode/ --allow-missing-repository

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: gitguardian.vsix
          path: gitguardian-*.vsix
