name: CI

on:
  pull_request:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pre-commit
        run: pipx run pre-commit run --all-files --show-diff-on-failure
        env:
          # SKIP ggshield check: it's done by the "scanning" job
          SKIP: ggshield

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            vscode_target: linux-x64
          - os: macos-latest
            vscode_target: darwin-arm64
          - os: windows-latest
            vscode_target: win32-x64

    steps:
      - name: 👩‍💻 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: ⚙️ Install dependencies
        run: yarn install

      - name: Download ggshield binary
        shell: bash
        run: scripts/download-ggshield.sh --target ${{ matrix.vscode_target }}

        # We use xvfb-run on Linux to run tests because we need a display.
        # xvfb-run is not available on macOS, so we use XQuartz instead.
        # The default GitHub Actions runner for Windows (windows-latest) has a GUI session
      - name: ⚙️ Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install xquartz xorg-server

      - name: 🧪 Run tests
        shell: bash # Ensure bash is used for Linux/macOS
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            xvfb-run --auto-servernum yarn test
          elif [ "$RUNNER_OS" = "macOS" ]; then
            bash ./scripts/xvfb-run-macos.sh yarn test
          else
            bash -c "yarn test"
          fi

  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    if: >-
      github.actor != 'dependabot[bot]' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
